FROM node:20-alpine

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build:docker

ENV DB_PASS $DB_PASS
ENV JWT_SECRET $JWT_SECRET
ENV CLOUDINARY_NAME $CLOUDINARY_NAME
ENV CLOUDINARY_API_KEY $CLOUDINARY_API_KEY
ENV CLOUDINARY_API_SECRET $CLOUDINARY_API_SECRET
ENV NODEMAILERUSER $NODEMAILERUSER
ENV NODEMAILERPASS $NODEMAILERPASS
ENV STRIPE_PUBLISHABLE_KEY $STRIPE_PUBLISHABLE_KEY
ENV CLIENT_ID $CLIENT_ID
ENV CLIENT_SECRET $CLIENT_SECRET
ENV REFRESH_TOKEN $REFRESH_TOKEN

ENV JWT_EXPIRE 5d
ENV COOKIE_EXPIRE 2

EXPOSE 8000

CMD [ "node","dist/index.js" ]

