global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "snapbid"
    scrape_interval: 15s
    static_configs:
      # - targets: ["snapbid:8000", "snap-bid.vercel.app"]
      - targets: ["snapbid:8000"]
  - job_name: "prod-snapbid"
    scrape_interval: 15s
    scheme: https
    static_configs:
      - targets: ["snapbid-backend.100xsushil.xyz/"]
